### ISSUE TITLE
Remove unused folders

### ISSUE THREAD

**Issue by naterush** [saga-vcs/saga-server#5]
Are `cli-server` and `testing_location_download` needed anymore? If not, let's remove them.

**Comment by naterush** [comment]
Are there folders within express server that aren't needed as well? This isn't an exhaustive list, but what are:`bin` or `public`? They might be used (and this might just be boiler plate), but if not let's rm them :)

**Comment by naterush** [comment]
In the same vein: consider where the package-lock file is for NPM? What's the standard placement of this file in node servers. Maybe let's do some digging on this subject...

**Comment by naterush** [comment]
What is "zip.d.ts"? It can be found in `saga-server/express-server/routes/zip.d.ts`. Not sure if it's boilerplate that's leftover of necessary.

**Comment by aarondr77** [comment]
Resolved in commit: b8b3a253ca7877791b0be408fb579e29e9bc13fc
