### ISSUE TITLE
Save all uploaded .saga projects in a single folder

### ISSUE THREAD

**Issue by naterush** [saga-vcs/saga-server#7]
As of now, uploading + creation of .saga projects creates them in the express server folder. This makes it hard to find things, and also has us uploading things to Github by accident. 

Proposal:
1. create a folder where all .saga projects go in. We can insisit on unique names for now -- or we can store them at username/projectname.

**Comment by aarondr77** [comment]
Resolved in commit: 9b1bf23a7b15ee2ae0ee57e7c8146020dd7fa5a6

Implemented "repositories" folder which contains a folder for each user with a repository. Each user folder contains their repositories.
